

# development:
#   adapter: sqlite3
#   database: db/development.sqlite
#   host: localhost
#   pool: 5
#   timeout: 5000

development:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  database: mydb_dev
  pool: 5
  username: erin
  password:
  timeout: 5000


production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  database: mydb_prod
  pool: 5
  username: erin
  password:
  timeout: 5000
